### ISSUE TITLE
Error on update

### ISSUE THREAD

**Issue by thekewe** [Cu3PO42/KeySAVe#75]
This is for KeySAVe on OS X. It prompts for an update but the update fails with this error popup:

```
A Javascript error occurred in the main process.
Uncaught Exception:
ReferenceError: callback is not defined
    at /Applications/KeySAVe.app/Contents/Resources/app/node_modules/electron-gh-releases-updater/index.js:86:104
    at ChildProcess.<anonymous> (/Applications/KeySAVe.app/Contents/Resources/app/node_modules/electron-gh-releases-updater/index.js:47:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by Cu3PO42** [comment]
I assume you are currently on 0.16.11. Unfortunately I didn't actually include the bugfix for that in the 0.16.11 version, so you'll have to update manually. It is fixed in 0.17.0, though. I will add a warning about this to the changelog. Thanks for reporting!
